//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangman.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files are up to date!.
        /// </summary>
        internal static string AllFilesAreUpToDate {
            get {
                return ResourceManager.GetString("AllFilesAreUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files have been synchronized!.
        /// </summary>
        internal static string AllFilesSynchronized {
            get {
                return ResourceManager.GetString("AllFilesSynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the words from the base have been drawn. 
        ///Do you want to start the draw from the beginning?.
        /// </summary>
        internal static string AllWordsDrawn {
            get {
                return ResourceManager.GetString("AllWordsDrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - choose dictionary!.
        /// </summary>
        internal static string ChooseDictionary {
            get {
                return ResourceManager.GetString("ChooseDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the chosen letter to guess the entry....
        /// </summary>
        internal static string ClickLetterToGuess {
            get {
                return ResourceManager.GetString("ClickLetterToGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click button on the left: &quot;NEW GAME&quot;, to start... .
        /// </summary>
        internal static string ClickNewGame {
            get {
                return ResourceManager.GetString("ClickNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary {0} has been created..
        /// </summary>
        internal static string DictionaryHasBeenCreated {
            get {
                return ResourceManager.GetString("DictionaryHasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong on download!.
        /// </summary>
        internal static string ErrorOnDownload {
            get {
                return ResourceManager.GetString("ErrorOnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorOnMsgBox {
            get {
                return ResourceManager.GetString("ErrorOnMsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong on upload!.
        /// </summary>
        internal static string ErrorOnUpload {
            get {
                return ResourceManager.GetString("ErrorOnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uno momento, I need to take some word from server....
        /// </summary>
        internal static string FetchingWord {
            get {
                return ResourceManager.GetString("FetchingWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP ME, please....
        /// </summary>
        internal static string HelpMe {
            get {
                return ResourceManager.GetString("HelpMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  dictionary: {0} | words#: {1}) &quot;.
        /// </summary>
        internal static string HowManyWOrdsInDictionary {
            get {
                return ResourceManager.GetString("HowManyWOrdsInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoOnMsgBox {
            get {
                return ResourceManager.GetString("InfoOnMsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert all needed values, like word, explanation and speech part!.
        /// </summary>
        internal static string InsertAllNeededValue {
            get {
                return ResourceManager.GetString("InsertAllNeededValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert word!.
        /// </summary>
        internal static string InsertWord {
            get {
                return ResourceManager.GetString("InsertWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have lost. The correct password is: {0}.
        /// </summary>
        internal static string LostGame {
            get {
                return ResourceManager.GetString("LostGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  There&apos;s no chosen dictionary name. Please write it in the text box or choose from the list of dictionaries after clicking on  &quot;≡Show all dictionaries&quot; button :).
        /// </summary>
        internal static string NoChosenDictionary {
            get {
                return ResourceManager.GetString("NoChosenDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to use your own dictionaries rather than downloading vocabulary from the internet, you must first select the one you are interested in. Usuallyto do this, click on the lowest small button on the left &quot;√|&quot; and select a dictionary in the window that opens. But now I’ll do it for you:).
        /// </summary>
        internal static string NoDictionarySelected {
            get {
                return ResourceManager.GetString("NoDictionarySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no dictionaries!\nYou have to write the name of the dictionary (like Animals or Verbs or what you want) in the field &quot;Dictionary name:&quot; and then click on the button &quot;‹Choose this dictionary&quot; to create it.&quot;.
        /// </summary>
        internal static string NoDirectoriesWriteName {
            get {
                return ResourceManager.GetString("NoDirectoriesWriteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK:).
        /// </summary>
        internal static string OKonMessageBox {
            get {
                return ResourceManager.GetString("OKonMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait a moment, because you try to get too many words in a short period of time. 
        ///Wait 60s, please ;).
        /// </summary>
        internal static string WaitForWord {
            get {
                return ResourceManager.GetString("WaitForWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh yeah, now it&apos;s OK:) 
        ///You can click on button &quot;NEW GAME&quot;!.
        /// </summary>
        internal static string WaitOver {
            get {
                return ResourceManager.GetString("WaitOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the winner, congratulations :).
        /// </summary>
        internal static string WinGame {
            get {
                return ResourceManager.GetString("WinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists in the dictionary!\n\nIf you only want to change the explanation or part of speech, click on the &quot;Save changes&quot; button after your modifications..
        /// </summary>
        internal static string WordAllreadyExists {
            get {
                return ResourceManager.GetString("WordAllreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word not found!.
        /// </summary>
        internal static string WordNotFound {
            get {
                return ResourceManager.GetString("WordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - i get words from internet.
        /// </summary>
        internal static string WordsFromInternetInfo {
            get {
                return ResourceManager.GetString("WordsFromInternetInfo", resourceCulture);
            }
        }
    }
}
